// <auto-generated />
using System;
using AccessoryWorld.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessoryWorld.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929223400_AddAiRetryCountToTradeInOnly")]
    partial class AddAiRetryCountToTradeInOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a minimal designer file for the targeted migration
            // The full model will be built from the current ApplicationDbContext
        }
    }
}